#!/bin/bash

readonly IMAGE="binocarlos/viking"
export DOCKER_URL=${DOCKER_URL:="https://get.docker.io/ubuntu/"}

install-docker(){
	curl -sSL $DOCKER_INSTALL | sudo sh
	sysctl -w net.ipv4.ip_forward=1
	echo "DOCKER_OPTS='-H unix:///var/run/docker.sock -H tcp://$VIKING_IP:$DOCKER_PORT'" > /etc/default/docker
	service docker restart
	sleep 2
}

pull-images(){
	docker pull binocarlos/etcd
	docker pull binocarlos/smesh
}

main() {
	set -eo pipefail
	install-docker
	pull-images
}

main "$@"