#!/bin/bash

readonly IMAGE="binocarlos/viking"
readonly DOCKER_INSTALL="https://get.docker.io/ubuntu/"
export DOCKER_PORT=${DOCKER_PORT:=2375}

check-environment(){
	if [ -z $HOSTNAME ]; then
		echo "HOSTNAME variable needed"
		exit 1
	fi
	if [ -z $VIKING_IP ]; then
		echo "VIKING_IP variable needed"
		exit 1
	fi
}

install-docker(){
	curl -sSL $DOCKER_INSTALL | sudo sh
	sysctl -w net.ipv4.ip_forward=1
	echo "DOCKER_OPTS='-H unix:///var/run/docker.sock -H tcp://$VIKING_IP:$DOCKER_PORT'" > /etc/default/docker
	service docker restart
	sleep 2
}

cmd-core() {
	check-environment
	install-docker
}

cmd-master() {
	echo "master"
}

cmd-slave() {
	echo "slave"
}

cmd-help() {
	cat <<EOF

usage: install COMMAND [args]

commands:

  core
  master
  slave

EOF
}

main() {
	set -eo pipefail
	case "$1" in
	core)               shift; cmd-core $@;;
	master)             shift; cmd-master $@;;
	slave)              shift; cmd-slave $@;;
	*)                  cmd-help $@;;
	esac
}

main "$@"